# Generated by Django 5.0.2 on 2026-02-09 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0005_company_schema_name_and_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "provider_type",
                    models.CharField(
                        help_text="Adapter identifier (ex: focusnfe, nfeio, plugnotas).",
                        max_length=60,
                    ),
                ),
                ("api_base_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fiscal Provider",
                "verbose_name_plural": "Fiscal Providers",
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="FiscalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ai_insights", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_id", models.PositiveBigIntegerField(db_index=True)),
                ("number", models.CharField(blank=True, max_length=40)),
                ("series", models.CharField(blank=True, max_length=20)),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("EMITTING", "Emitting"),
                            ("AUTHORIZED", "Authorized"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "xml_document_id",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "External XML document reference (Cloud Storage object path, "
                            "documents module id, etc.)."
                        ),
                        max_length=200,
                    ),
                ),
                (
                    "xml_content",
                    models.TextField(
                        blank=True,
                        help_text="Raw XML content snapshot stored for audit and interoperability.",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Document",
                "verbose_name_plural": "Fiscal Documents",
                "ordering": ("-issue_date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="TenantFiscalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ai_insights", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("api_token", models.TextField(blank=True)),
                (
                    "environment",
                    models.CharField(
                        choices=[("SANDBOX", "Sandbox"), ("PRODUCTION", "Production")],
                        db_index=True,
                        default="SANDBOX",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.company",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_configs",
                        to="finance_fiscal.fiscalprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Fiscal Config",
                "verbose_name_plural": "Tenant Fiscal Configs",
                "ordering": ("-active", "-updated_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="FiscalCustomerSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ai_insights", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("cpf_cnpj", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.company",
                    ),
                ),
                (
                    "fiscal_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_snapshot",
                        to="finance_fiscal.fiscaldocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Customer Snapshot",
                "verbose_name_plural": "Fiscal Customer Snapshots",
                "ordering": ("-id",),
            },
        ),
        migrations.AddConstraint(
            model_name="fiscalprovider",
            constraint=models.UniqueConstraint(
                fields=("provider_type",),
                name="uq_fiscal_provider_type",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantfiscalconfig",
            index=models.Index(
                fields=("company", "active", "environment"),
                name="idx_tenant_fiscal_config_active_env",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantfiscalconfig",
            constraint=models.UniqueConstraint(
                fields=("company", "provider"),
                name="uq_tenant_fiscal_config_provider_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantfiscalconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("company",),
                name="uq_tenant_fiscal_config_single_active_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscaldocument",
            index=models.Index(fields=("company", "invoice_id"), name="idx_fiscal_doc_invoice"),
        ),
        migrations.AddIndex(
            model_name="fiscaldocument",
            index=models.Index(
                fields=("company", "status", "issue_date"), name="idx_fiscal_doc_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscaldocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("company", "series", "number"),
                name="uq_fiscal_doc_number_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalcustomersnapshot",
            index=models.Index(fields=("company", "cpf_cnpj"), name="idx_fiscal_snap_cpfcnpj"),
        ),
    ]

