# Generated by Django 5.0.2 on 2026-02-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_fiscal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscaldocument",
            name="provider_document_id",
            field=models.CharField(
                blank=True,
                help_text="External provider document id used for status/cancellation calls.",
                max_length=200,
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscaldocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_document_id", ""), _negated=True),
                fields=("company", "provider_document_id"),
                name="uq_fiscal_doc_provider_document_id_per_tenant",
            ),
        ),
    ]

