# Generated by Django 5.0.2 on 2026-02-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_fiscal", "0002_fiscaldocument_provider_document_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantfiscalconfig",
            name="auto_issue",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If true, automatically issue NF when an invoice is marked as PAID.",
            ),
        ),
    ]

