# Generated by Django 5.0.2 on 2026-02-09 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance_fiscal", "0003_tenantfiscalconfig_auto_issue"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenantfiscalconfig",
            old_name="idx_tenant_fiscal_config_active_env",
            new_name="idx_fiscfg_act_env",
        ),
    ]

