# Generated by Django 5.0.2 on 2026-02-09 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
        ('finance_fiscal', '0004_tenantfiscalconfig_rename_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantfiscalconfig',
            name='api_token',
            field=models.TextField(blank=True, help_text='Encrypted API token for the provider (do not store plaintext).'),
        ),
        migrations.CreateModel(
            name='FiscalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('fiscal_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='finance_fiscal.fiscaldocument')),
            ],
            options={
                'verbose_name': 'Fiscal Job',
                'verbose_name_plural': 'Fiscal Jobs',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['company', 'status', 'next_retry_at'], name='idx_fjob_status_retry')],
            },
        ),
    ]
