# Generated by Django 5.0.2 on 2026-02-09 13:50

import django.core.serializers.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ck_ledger_scope_company',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='data_after',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='data_before',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('company__isnull', False), ('scope', 'TENANT')), models.Q(('company__isnull', True), ('scope', 'PLATFORM')), _connector='OR'), name='ck_ledger_scope_company'),
        ),
    ]
