# Generated by Codex on 2026-02-09

from django.db import migrations


CREATE_FUNCTION_SQL = r"""
CREATE OR REPLACE FUNCTION mks_ledger_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'Ledger entries are immutable (UPDATE/DELETE is not allowed).';
END;
$$;
"""

CREATE_TRIGGER_SQL = r"""
DO $$
BEGIN
  -- The table only exists in tenant schemas (django-tenants). If this migration is
  -- evaluated on the public schema, this is a safe no-op.
  IF to_regclass('ledger_ledgerentry') IS NOT NULL THEN
    DROP TRIGGER IF EXISTS trg_ledger_immutable ON ledger_ledgerentry;
    CREATE TRIGGER trg_ledger_immutable
      BEFORE UPDATE OR DELETE ON ledger_ledgerentry
      FOR EACH ROW
      EXECUTE FUNCTION mks_ledger_reject_mutation();
  END IF;
END $$;
"""

DROP_TRIGGER_SQL = r"""
DO $$
BEGIN
  IF to_regclass('ledger_ledgerentry') IS NOT NULL THEN
    DROP TRIGGER IF EXISTS trg_ledger_immutable ON ledger_ledgerentry;
  END IF;
END $$;
"""

DROP_FUNCTION_SQL = r"DROP FUNCTION IF EXISTS mks_ledger_reject_mutation();"


def _is_postgres(schema_editor) -> bool:
    return getattr(schema_editor.connection, "vendor", "") == "postgresql"


def forwards_create_db_immutability(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    schema_editor.execute(CREATE_FUNCTION_SQL)
    schema_editor.execute(CREATE_TRIGGER_SQL)


def backwards_drop_db_immutability(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    schema_editor.execute(DROP_TRIGGER_SQL)
    schema_editor.execute(DROP_FUNCTION_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0002_remove_ledgerentry_ck_ledger_scope_company_and_more"),
    ]

    operations = [
        migrations.RunPython(
            forwards_create_db_immutability,
            backwards_drop_db_immutability,
        ),
    ]
