# Generated by Django 5.0.2 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "tenant_code",
                    models.SlugField(
                        help_text="Identifier used in the X-Tenant-ID header.",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "subdomain",
                    models.SlugField(
                        help_text="Tenant subdomain used for host-based tenant resolution.",
                        max_length=63,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ("name",),
            },
        ),
    ]
