# Generated by Django 5.0.2 on 2026-02-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_companymembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="rbac_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Optional tenant RBAC overrides. "
                    "Example: {'apolices': {'POST': ['OWNER', 'MANAGER']}}"
                ),
            ),
        ),
    ]
