# Generated by Django 5.0.2 on 2026-02-08 02:08

import tenancy.rbac
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_company_rbac_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rbac_overrides',
            field=models.JSONField(blank=True, default=dict, help_text="Optional tenant RBAC overrides. Example: {'apolices': {'POST': ['OWNER', 'MANAGER']}}", validators=[tenancy.rbac.validate_rbac_overrides_schema]),
        ),
    ]
