# Generated by Codex on 2026-02-09

import re

import django.db.models.deletion
from django.db import migrations, models

try:  # pragma: no cover - migration import guard
    from django_tenants.postgresql_backend.base import _check_schema_name
except Exception:  # pragma: no cover - fallback (keeps migration importable)
    _check_schema_name = lambda _value: None  # noqa: E731


def _normalize_schema_name(value: str) -> str:
    normalized = (value or "").strip().lower()
    normalized = re.sub(r"[^a-z0-9_-]+", "-", normalized).strip("-")
    return normalized[:63] if normalized else normalized


def forwards_populate_schema_and_domains(apps, _schema_editor):
    Company = apps.get_model("customers", "Company")
    Domain = apps.get_model("customers", "Domain")

    for company in Company.objects.all().only("id", "tenant_code", "subdomain"):
        schema_name = _normalize_schema_name(company.tenant_code)
        if not schema_name:
            schema_name = f"tenant_{company.id}"

        Company.objects.filter(id=company.id).update(schema_name=schema_name)

        # Create a deterministic local dev domain for every tenant.
        local_domain = f"{company.subdomain}.localhost"
        Domain.objects.get_or_create(
            domain=local_domain,
            defaults={"tenant_id": company.id, "is_primary": True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_alter_company_rbac_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                max_length=63,
                null=True,
                unique=True,
                validators=[_check_schema_name],
            ),
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=253, unique=True)),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="customers.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Domain",
                "verbose_name_plural": "Tenant Domains",
            },
        ),
        migrations.RunPython(
            forwards_populate_schema_and_domains,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="company",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                max_length=63,
                unique=True,
                validators=[_check_schema_name],
            ),
        ),
    ]

