# Generated by Django 5.0.2 on 2026-02-12 20:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('team_name', models.CharField(blank=True, max_length=120)),
                ('is_team_manager', models.BooleanField(default=False)),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('street_number', models.CharField(blank=True, max_length=30)),
                ('address_complement', models.CharField(blank=True, max_length=120)),
                ('commission_transfer_percent', models.DecimalField(decimal_places=2, help_text='Percentual do repasse sobre a comissão da empresa.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('payout_hold_days', models.PositiveSmallIntegerField(default=3)),
                ('bank_code', models.CharField(blank=True, max_length=4)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_agency', models.CharField(blank=True, max_length=20)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('bank_account_type', models.CharField(blank=True, choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Conta Poupança'), ('PAYMENT', 'Conta Pagamento')], max_length=20)),
                ('pix_key_type', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'Email'), ('PHONE', 'Telefone'), ('RANDOM', 'Chave Aleatória')], max_length=20)),
                ('pix_key', models.CharField(blank=True, max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_profiles', to='customers.company')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer_profile', to='customers.companymembership')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='producerprofile',
            constraint=models.UniqueConstraint(fields=('company', 'cpf'), name='uq_producer_profile_company_cpf'),
        ),
    ]
