# Generated by Django 5.0.2 on 2026-02-09 23:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower values win when multiple plans match.')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rules_json', models.JSONField(blank=True, default=dict, help_text='Commission rules payload (JSONB on Postgres).')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
            ],
            options={
                'verbose_name': 'Commission Plan',
                'verbose_name_plural': 'Commission Plans',
                'ordering': ('priority', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CommissionPlanScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.CharField(choices=[('ANY', 'Any'), ('LINE_OF_BUSINESS', 'Line of Business'), ('INSURER', 'Insurer'), ('PRODUCT', 'Product'), ('SALES_CHANNEL', 'Sales Channel'), ('CUSTOM', 'Custom')], db_index=True, default='ANY', max_length=40)),
                ('value', models.CharField(blank=True, help_text="Scope value for the selected dimension. Empty means 'ANY'.", max_length=255)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower values win when multiple scopes match within a plan.')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rules_json', models.JSONField(blank=True, default=dict, help_text='Optional overrides for the plan rules when this scope matches.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='commission.commissionplan')),
            ],
            options={
                'verbose_name': 'Commission Plan Scope',
                'verbose_name_plural': 'Commission Plan Scopes',
                'ordering': ('priority', 'dimension', 'value', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CommissionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_type', models.CharField(choices=[('USER', 'User'), ('ROLE', 'Role'), ('EXTERNAL', 'External')], db_index=True, max_length=20)),
                ('recipient_ref', models.CharField(help_text='Opaque recipient reference (e.g. user_id, role code, external id).', max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower values win when multiple splits match within a scope.')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rules_json', models.JSONField(blank=True, default=dict, help_text='Optional split-specific rules/metadata.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='commission.commissionplanscope')),
            ],
            options={
                'verbose_name': 'Commission Split',
                'verbose_name_plural': 'Commission Splits',
                'ordering': ('priority', 'recipient_type', 'recipient_ref', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='commissionplan',
            index=models.Index(fields=['company', 'status'], name='idx_comm_plan_company_status'),
        ),
        migrations.AddIndex(
            model_name='commissionplan',
            index=models.Index(fields=['company', 'effective_from'], name='idx_comm_plan_company_eff'),
        ),
        migrations.AddConstraint(
            model_name='commissionplan',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_comm_plan_company_name'),
        ),
        migrations.AddConstraint(
            model_name='commissionplan',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_comm_plan_eff_range'),
        ),
        migrations.AddIndex(
            model_name='commissionplanscope',
            index=models.Index(fields=['company', 'plan'], name='idx_comm_scope_company_plan'),
        ),
        migrations.AddIndex(
            model_name='commissionplanscope',
            index=models.Index(fields=['company', 'dimension'], name='idx_comm_scope_company_dim'),
        ),
        migrations.AddConstraint(
            model_name='commissionplanscope',
            constraint=models.UniqueConstraint(fields=('company', 'plan', 'dimension', 'value', 'effective_from'), name='uq_comm_scope_key'),
        ),
        migrations.AddConstraint(
            model_name='commissionplanscope',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_comm_scope_eff_range'),
        ),
        migrations.AddIndex(
            model_name='commissionsplit',
            index=models.Index(fields=['company', 'scope'], name='idx_comm_split_company_scope'),
        ),
        migrations.AddIndex(
            model_name='commissionsplit',
            index=models.Index(fields=['company', 'recipient_type', 'recipient_ref'], name='idx_comm_split_recipient'),
        ),
        migrations.AddConstraint(
            model_name='commissionsplit',
            constraint=models.UniqueConstraint(fields=('company', 'scope', 'recipient_type', 'recipient_ref', 'effective_from'), name='uq_comm_split_key'),
        ),
        migrations.AddConstraint(
            model_name='commissionsplit',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_comm_split_eff_range'),
        ),
    ]
