# Generated by Django 5.0.2 on 2026-02-09 14:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('integration_type', models.CharField(choices=[('NONE', 'None'), ('API', 'API'), ('MANUAL', 'Manual'), ('BROKER_PORTAL', 'Broker Portal')], default='NONE', max_length=20)),
                ('integration_config', models.JSONField(blank=True, default=dict, help_text='Integration config (store Secret Manager references, never raw secrets).')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
            ],
            options={
                'verbose_name': 'Insurer',
                'verbose_name_plural': 'Insurers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('line_of_business', models.CharField(choices=[('AUTO', 'Auto'), ('LIFE', 'Vida'), ('HEALTH', 'Saude'), ('PROPERTY', 'Patrimonial'), ('TRANSPORT', 'Transporte'), ('LIABILITY', 'RC'), ('OTHER', 'Outro')], max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='insurance_core.insurer')),
            ],
            options={
                'verbose_name': 'Insurance Product',
                'verbose_name_plural': 'Insurance Products',
                'ordering': ('line_of_business', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('coverage_type', models.CharField(choices=[('BASIC', 'Basic'), ('ADDITIONAL', 'Additional'), ('ASSIST', 'Assist')], default='BASIC', max_length=20)),
                ('default_limit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('default_deductible_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('required', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='insurance_core.insuranceproduct')),
            ],
            options={
                'verbose_name': 'Product Coverage',
                'verbose_name_plural': 'Product Coverages',
                'ordering': ('product__id', 'code'),
            },
        ),
        migrations.AddIndex(
            model_name='insurer',
            index=models.Index(fields=['company', 'status'], name='idx_insurer_company_status'),
        ),
        migrations.AddConstraint(
            model_name='insurer',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_insurer_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='insuranceproduct',
            index=models.Index(fields=['company', 'line_of_business'], name='idx_product_company_lob'),
        ),
        migrations.AddConstraint(
            model_name='insuranceproduct',
            constraint=models.UniqueConstraint(fields=('company', 'insurer', 'code'), name='uq_insurance_product_code_per_insurer_company'),
        ),
        migrations.AddConstraint(
            model_name='productcoverage',
            constraint=models.UniqueConstraint(fields=('company', 'product', 'code'), name='uq_product_coverage_code_per_product_company'),
        ),
    ]
