# Generated by Django 5.0.2 on 2026-02-09 17:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
        ('insurance_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(blank=True, help_text='Policy number assigned by the insurer (nullable until issued).', max_length=80, null=True)),
                ('insured_party_id', models.PositiveBigIntegerField(db_index=True, help_text='Reference to the insured party (Customer ID in the CRM bounded context).')),
                ('insured_party_label', models.CharField(blank=True, help_text='Snapshot label (ex: customer name) to avoid cross-context joins in listings.', max_length=255)),
                ('broker_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDERWRITING', 'Underwriting'), ('ISSUED', 'Issued'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('premium_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance_core.insurer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance_core.insuranceproduct')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endorsement_number', models.CharField(blank=True, help_text='Endorsement number assigned by the insurer (nullable until issued).', max_length=50, null=True)),
                ('type', models.CharField(choices=[('COVERAGE_CHANGE', 'Coverage change'), ('INSURED_OBJECT_CHANGE', 'Insured object change'), ('FINANCIAL_CHANGE', 'Financial change'), ('CANCELLATION_LIKE', 'Cancellation-like')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('effective_date', models.DateField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='insurance_core.policy')),
            ],
            options={
                'verbose_name': 'Endorsement',
                'verbose_name_plural': 'Endorsements',
                'ordering': ('-effective_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PolicyCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deductible_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('premium_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='insurance_core.policy')),
                ('product_coverage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_coverages', to='insurance_core.productcoverage')),
            ],
            options={
                'verbose_name': 'Policy Coverage',
                'verbose_name_plural': 'Policy Coverages',
                'ordering': ('policy_id', 'product_coverage_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PolicyDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_code', models.CharField(max_length=80)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('document_id', models.CharField(blank=True, help_text='Reference to documents module (future).', max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='insurance_core.policy')),
            ],
            options={
                'verbose_name': 'Policy Document Requirement',
                'verbose_name_plural': 'Policy Document Requirements',
                'ordering': ('policy_id', 'status', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PolicyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('AUTO', 'Auto'), ('PROPERTY', 'Property'), ('LIFE', 'Life'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('sum_insured', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='insurance_core.policy')),
            ],
            options={
                'verbose_name': 'Policy Item',
                'verbose_name_plural': 'Policy Items',
                'ordering': ('policy_id', 'item_type', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company', 'status', 'start_date'], name='idx_pol_cmp_stat_start'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company', 'insurer', 'product'], name='idx_pol_cmp_ins_prod'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('policy_number__isnull', True), _negated=True), models.Q(('policy_number', ''), _negated=True)), fields=('company', 'policy_number'), name='uq_policy_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='endorsement',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('endorsement_number__isnull', True), _negated=True), models.Q(('endorsement_number', ''), _negated=True)), fields=('company', 'policy', 'endorsement_number'), name='uq_endorsement_number_per_policy_company'),
        ),
        migrations.AddConstraint(
            model_name='policycoverage',
            constraint=models.UniqueConstraint(fields=('company', 'policy', 'product_coverage'), name='uq_policy_coverage_per_policy_company'),
        ),
        migrations.AddIndex(
            model_name='policydocumentrequirement',
            index=models.Index(fields=['company', 'policy', 'status'], name='idx_pdoc_cmp_pol_stat'),
        ),
        migrations.AddConstraint(
            model_name='policydocumentrequirement',
            constraint=models.UniqueConstraint(fields=('company', 'policy', 'requirement_code'), name='uq_policy_doc_requirement_code_per_policy_company'),
        ),
        migrations.AddIndex(
            model_name='policyitem',
            index=models.Index(fields=['company', 'policy', 'item_type'], name='idx_pitem_cmp_pol_type'),
        ),
    ]
