# Generated by Django 5.0.2 on 2026-02-09 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
        ('insurance_core', '0002_policy_endorsement_policycoverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='address_complement',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='insurer',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='insurer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='insurer',
            name='state',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='insurer',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='insurer',
            name='street_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='insurer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name='InsurerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='insurance_core.insurer')),
            ],
            options={
                'ordering': ('-is_primary', 'name', 'id'),
                'indexes': [models.Index(fields=['company', 'insurer'], name='idx_insurer_contact_insurer')],
            },
        ),
        migrations.AddConstraint(
            model_name='insurercontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('company', 'insurer'), name='uq_insurer_primary_contact_per_insurer'),
        ),
    ]
