# Generated by Django 5.0.2 on 2026-02-10 03:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
        ('insurance_core', '0003_insurer_address_complement_insurer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(db_index=True, max_length=50)),
                ('occurrence_date', models.DateField()),
                ('report_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_REVIEW', 'Em Análise'), ('APPROVED', 'Aprovado'), ('DENIED', 'Negado'), ('PAID', 'Pago'), ('CLOSED', 'Encerrado')], default='OPEN', max_length=20)),
                ('status_notes', models.TextField(blank=True, help_text='Motivo da decisão ou notas de status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance_core.policy')),
            ],
            options={
                'verbose_name': 'Sinistro',
                'verbose_name_plural': 'Sinistros',
                'ordering': ('-report_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InsuranceBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='Código SUSEP', max_length=20)),
                ('branch_type', models.CharField(choices=[('NORMAL', 'Seguro Geral'), ('HEALTH', 'Plano de Saúde')], default='NORMAL', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
            ],
            options={
                'verbose_name': 'Ramo de Seguro',
                'verbose_name_plural': 'Ramos de Seguro',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PolicyBillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_installment_due_date', models.DateField()),
                ('installments_count', models.PositiveSmallIntegerField(default=1, help_text='Número de parcelas (1 a 12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('premium_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_rate_percent', models.DecimalField(decimal_places=2, help_text='Percentual de comissão acordado', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('original_premium_total', models.DecimalField(blank=True, decimal_places=2, help_text='Prêmio original da apólice (sem endossos) para cálculo de base de comissão (Health)', max_digits=14, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_config', to='insurance_core.policy')),
            ],
            options={
                'verbose_name': 'Configuração de Faturamento',
                'verbose_name_plural': 'Configurações de Faturamento',
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('POLICY', 'Apólice (PDF)'), ('ENDORSEMENT', 'Endosso (PDF)'), ('CLAIM', 'Sinistro'), ('BILL', 'Boleto'), ('OTHER', 'Outros')], default='OTHER', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(help_text='Caminho relativo no bucket (ex: tenants/1/policies/doc.pdf)', max_length=512)),
                ('bucket_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, help_text='Checksum (MD5/SHA256) for integrity', max_length=64)),
                ('uploaded_at', models.DateTimeField(blank=True, help_text='When upload was confirmed', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='insurance_core.claim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('endorsement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='insurance_core.endorsement')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='insurance_core.policy')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DomainEventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['company', 'published_at'], name='insurance_c_company_ca1bf1_idx'), models.Index(fields=['company', 'event_type'], name='insurance_c_company_c85e02_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='insurancebranch',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_insurance_branch_code_company'),
        ),
    ]
