# Generated by Django 5.0.2 on 2026-02-08 04:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_alter_company_rbac_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELED', 'Canceled')], default='TRIAL', max_length=20)),
                ('seats', models.PositiveIntegerField(default=3)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='customers.company')),
            ],
            options={
                'verbose_name': 'Tenant Contract',
                'verbose_name_plural': 'Tenant Contracts',
                'ordering': ('company__name',),
            },
        ),
        migrations.CreateModel(
            name='TenantProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolation_model', models.CharField(choices=[('SHARED_SCHEMA', 'Shared DB / Shared Schema'), ('DATABASE_PER_TENANT', 'Database per Tenant')], default='DATABASE_PER_TENANT', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONING', 'Provisioning'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('database_alias', models.SlugField(max_length=63, unique=True)),
                ('database_name', models.CharField(max_length=100)),
                ('database_host', models.CharField(default='127.0.0.1', max_length=255)),
                ('database_port', models.PositiveIntegerField(default=5432)),
                ('database_user', models.CharField(max_length=100)),
                ('database_password_secret', models.CharField(blank=True, max_length=255)),
                ('portal_url', models.URLField(blank=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning', to='customers.company')),
            ],
            options={
                'verbose_name': 'Tenant Provisioning',
                'verbose_name_plural': 'Tenant Provisioning',
                'ordering': ('company__name',),
            },
        ),
    ]
