# Generated by Django 5.0.2 on 2026-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprovisioning',
            name='isolation_model',
            field=models.CharField(choices=[('SCHEMA_PER_TENANT', 'Shared DB / Schema per Tenant'), ('DATABASE_PER_TENANT', 'Database per Tenant'), ('SHARED_SCHEMA', 'Shared DB / Shared Schema (legacy)')], default='SCHEMA_PER_TENANT', max_length=30),
        ),
    ]
