# Generated by Django 5.0.2 on 2026-02-10 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0002_alter_tenantprovisioning_isolation_model'),
        ('customers', '0005_company_schema_name_and_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tier', models.CharField(choices=[('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('ENTERPRISE', 'Enterprise')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['tier', 'is_active'], name='cp_plan_tier_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='control_plane.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=180)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('subdomain', models.SlugField(max_length=63, unique=True)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('street', models.CharField(blank=True, max_length=180)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_tenant', to='customers.company')),
            ],
            options={
                'ordering': ('legal_name',),
            },
        ),
        migrations.CreateModel(
            name='TenantPlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateField(blank=True, null=True)),
                ('is_courtesy', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='control_plane.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='control_plane.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('DELETED', 'Deleted')], max_length=20)),
                ('to_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('DELETED', 'Deleted')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_status_changes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='control_plane.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.CheckConstraint(check=models.Q(('monthly_price__in', [150, 250, 350])), name='cp_plan_price_monthly_allowed'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.CheckConstraint(check=models.Q(('setup_fee__in', [0, 150])), name='cp_plan_price_setup_allowed'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status'], name='cp_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug'], name='cp_tenant_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['company', 'status'], name='cp_tenant_company_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(check=models.Q(('slug', ''), _negated=True), name='cp_tenant_slug_not_blank'),
        ),
        migrations.AddIndex(
            model_name='tenantplansubscription',
            index=models.Index(fields=['tenant', 'status'], name='cp_sub_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantplansubscription',
            index=models.Index(fields=['tenant', 'start_date'], name='cp_sub_tenant_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantplansubscription',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='cp_tenant_sub_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='tenantstatushistory',
            index=models.Index(fields=['tenant', 'created_at'], name='cp_tsh_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantstatushistory',
            index=models.Index(fields=['to_status'], name='cp_tsh_to_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantstatushistory',
            constraint=models.CheckConstraint(check=models.Q(('from_status', models.F('to_status')), _negated=True), name='cp_tenant_status_hist_from_to_diff'),
        ),
    ]
