# Generated by Django 5.0.2 on 2026-02-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0004_controlpanelauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpanelauditlog',
            name='action',
            field=models.CharField(choices=[('LIST', 'List'), ('RETRIEVE', 'Retrieve'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('SUSPEND', 'Suspend'), ('UNSUSPEND', 'Unsuspend'), ('SOFT_DELETE', 'Soft delete')], max_length=20),
        ),
    ]
