# Generated by Django 5.0.2 on 2026-02-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0005_alter_controlpanelauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantplansubscription',
            name='setup_fee_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='tenantplansubscription',
            constraint=models.CheckConstraint(check=models.Q(('setup_fee_override__isnull', True), ('setup_fee_override__gte', 0), _connector='OR'), name='cp_tenant_sub_setup_fee_non_negative'),
        ),
    ]
