# Generated by Django 5.0.2 on 2026-02-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0006_tenantplansubscription_setup_fee_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('SIGNED', 'Signed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('contract_version', models.PositiveIntegerField(default=1)),
                ('snapshot_json', models.JSONField(default=dict)),
                ('pdf_document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='control_plane.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContractEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('resend_message_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='control_plane.tenantcontractdocument')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='tenantcontractdocument',
            index=models.Index(fields=['tenant', 'status'], name='cp_contract_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcontractdocument',
            index=models.Index(fields=['tenant', 'created_at'], name='cp_contract_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='contractemaillog',
            index=models.Index(fields=['contract', 'status'], name='cp_contract_email_status_idx'),
        ),
    ]
