# Generated by Django 5.0.2 on 2026-02-10 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0007_tenantcontractdocument_contractemaillog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('latency_ms', models.FloatField(default=0)),
                ('error_rate', models.FloatField(default=0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-captured_at',),
                'indexes': [models.Index(fields=['service_name', 'captured_at'], name='cp_sys_health_service_ts_idx'), models.Index(fields=['status', 'captured_at'], name='cp_sys_health_status_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('request_rate', models.FloatField(default=0)),
                ('error_rate', models.FloatField(default=0)),
                ('p95_latency', models.FloatField(default=0)),
                ('jobs_pending', models.IntegerField(default=0)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='control_plane.tenant')),
            ],
            options={
                'ordering': ('-captured_at',),
                'indexes': [models.Index(fields=['tenant', 'captured_at'], name='cp_tenant_health_tenant_ts_idx'), models.Index(fields=['captured_at'], name='cp_tenant_health_ts_idx')],
            },
        ),
    ]
