# Generated by Django 5.0.2 on 2026-02-10 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0008_systemhealthsnapshot_tenanthealthsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'key'], name='cp_feature_active_key_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantInternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_internal_notes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='control_plane.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdminAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to=settings.AUTH_USER_MODEL)),
                ('target_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to='control_plane.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_tenant', 'created_at'], name='cp_admin_audit_tenant_ts_idx'), models.Index(fields=['action', 'created_at'], name='cp_admin_audit_action_ts_idx'), models.Index(fields=['entity_type', 'entity_id'], name='cp_admin_audit_entity_idx'), models.Index(fields=['correlation_id'], name='cp_admin_audit_corr_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_flags', to='control_plane.featureflag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='control_plane.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_feature_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('feature__name',),
                'indexes': [models.Index(fields=['tenant', 'enabled'], name='cp_tenant_feature_enabled_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tenantfeatureflag',
            constraint=models.UniqueConstraint(fields=('tenant', 'feature'), name='cp_tenant_feature_unique'),
        ),
        migrations.AddIndex(
            model_name='tenantinternalnote',
            index=models.Index(fields=['tenant', 'created_at'], name='cp_note_tenant_ts_idx'),
        ),
    ]
