# Generated by Django 5.0.2 on 2026-02-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0009_featureflag_tenantinternalnote_adminauditevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
