# Generated by Django 5.0.2 on 2026-02-10 21:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0010_tenant_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantImpersonationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_impersonation_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions', to='control_plane.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantIntegrationSecretRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('RESEND', 'Resend'), ('WHATSAPP', 'WhatsApp'), ('VERTEX_AI', 'Vertex AI'), ('CUSTOM', 'Custom')], max_length=30)),
                ('alias', models.SlugField(default='default', max_length=80)),
                ('secret_manager_ref', models.CharField(help_text='GCP Secret Manager reference, never store raw credentials.', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_integration_secret_refs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_secrets', to='control_plane.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantOperationalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_per_minute', models.PositiveIntegerField(default=600)),
                ('storage_limit_gb', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('docs_storage_limit_gb', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('module_limits_json', models.JSONField(blank=True, default=dict)),
                ('current_storage_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_docs_storage_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_storage_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operational_settings', to='control_plane.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_operational_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantReleaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_version', models.CharField(max_length=64)),
                ('frontend_version', models.CharField(blank=True, max_length=64)),
                ('git_sha', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(default='cloud_run', max_length=32)),
                ('changelog', models.TextField(blank=True)),
                ('changelog_json', models.JSONField(blank=True, default=list)),
                ('is_current', models.BooleanField(default=True)),
                ('deployed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_release_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_records', to='control_plane.tenant')),
            ],
            options={
                'ordering': ('-deployed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TenantAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('NO_HEARTBEAT', 'No heartbeat'), ('HIGH_ERROR_RATE', 'High error rate'), ('RATE_LIMIT_EXCEEDED', 'Rate limit exceeded'), ('STORAGE_LIMIT_EXCEEDED', 'Storage limit exceeded'), ('STORAGE_LIMIT_NEAR', 'Storage limit near threshold')], max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('message', models.TextField()),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='control_plane.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='cp_alert_tenant_status_idx'), models.Index(fields=['alert_type', 'status'], name='cp_alert_type_status_idx'), models.Index(fields=['last_seen_at'], name='cp_alert_last_seen_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tenantalertevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'alert_type', 'status'), name='cp_alert_unique_open_status'),
        ),
        migrations.AddIndex(
            model_name='tenantimpersonationsession',
            index=models.Index(fields=['tenant', 'status'], name='cp_imp_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantimpersonationsession',
            index=models.Index(fields=['actor', 'status'], name='cp_imp_actor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantimpersonationsession',
            index=models.Index(fields=['expires_at'], name='cp_imp_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantintegrationsecretref',
            index=models.Index(fields=['tenant', 'provider'], name='cp_int_tenant_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantintegrationsecretref',
            index=models.Index(fields=['tenant', 'is_active'], name='cp_int_tenant_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantintegrationsecretref',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'alias'), name='cp_tenant_integration_ref_unique'),
        ),
        migrations.AddIndex(
            model_name='tenantoperationalsettings',
            index=models.Index(fields=['tenant'], name='cp_ops_settings_tenant_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantoperationalsettings',
            constraint=models.CheckConstraint(check=models.Q(('requests_per_minute__gte', 1)), name='cp_ops_settings_rpm_positive'),
        ),
        migrations.AddConstraint(
            model_name='tenantoperationalsettings',
            constraint=models.CheckConstraint(check=models.Q(('storage_limit_gb__gte', 0)), name='cp_ops_settings_storage_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenantoperationalsettings',
            constraint=models.CheckConstraint(check=models.Q(('docs_storage_limit_gb__gte', 0)), name='cp_ops_settings_docs_storage_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenantoperationalsettings',
            constraint=models.CheckConstraint(check=models.Q(('current_storage_gb__gte', 0)), name='cp_ops_settings_current_storage_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenantoperationalsettings',
            constraint=models.CheckConstraint(check=models.Q(('current_docs_storage_gb__gte', 0)), name='cp_ops_settings_current_docs_storage_non_negative'),
        ),
        migrations.AddIndex(
            model_name='tenantreleaserecord',
            index=models.Index(fields=['tenant', 'is_current'], name='cp_release_tenant_current_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantreleaserecord',
            index=models.Index(fields=['tenant', 'deployed_at'], name='cp_release_tenant_deployed_idx'),
        ),
    ]
