# Generated by Django 5.0.2 on 2026-02-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0011_tenantimpersonationsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantintegrationsecretref',
            name='provider',
            field=models.CharField(choices=[('SMTP', 'SMTP'), ('WHATSAPP', 'WhatsApp'), ('VERTEX_AI', 'Vertex AI'), ('CUSTOM', 'Custom')], max_length=30),
        ),
    ]
