# Generated by Django 5.0.2 on 2026-02-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Apólice')),
                ('seguradora', models.CharField(max_length=100)),
                ('ramo', models.CharField(max_length=50)),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_cpf_cnpj', models.CharField(max_length=20)),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('status', models.CharField(choices=[('COTACAO', 'Em Cotação'), ('PENDENTE', 'Pendente de Emissão'), ('ATIVA', 'Vigente'), ('CANCELADA', 'Cancelada'), ('RENOVADA', 'Renovada'), ('NAO_RENOVADA', 'Não Renovada')], default='COTACAO', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
            ],
            options={
                'verbose_name': 'Apólice',
                'verbose_name_plural': 'Apólices',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('document', models.CharField(blank=True, max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Endosso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_endosso', models.CharField(default='0', max_length=20)),
                ('tipo', models.CharField(choices=[('EMISSAO', 'Emissão Inicial'), ('RENOVACAO', 'Renovação'), ('INCLUSAO', 'Endosso de Inclusão'), ('EXCLUSAO', 'Endosso de Exclusão'), ('CANCELAMENTO', 'Cancelamento'), ('FATURAMENTO', 'Ajuste de Faturamento'), ('SEM_MOVIMENTO', 'Alteração Cadastral')], max_length=20)),
                ('premio_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iof', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('premio_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_emissao', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('apolice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endossos', to='operational.apolice')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
            ],
            options={
                'verbose_name': 'Endosso',
                'verbose_name_plural': 'Endossos',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('QUALIFIED', 'Qualificado'), ('DISQUALIFIED', 'Desqualificado'), ('CONVERTED', 'Convertido')], default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='operational.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('DISCOVERY', 'Descoberta'), ('PROPOSAL', 'Proposta'), ('NEGOTIATION', 'Negociação'), ('WON', 'Ganha'), ('LOST', 'Perdida')], default='DISCOVERY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='operational.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='apolice',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('company', 'numero'), name='uq_apolice_numero_per_company'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'email'), name='uq_customer_email_per_company'),
        ),
        migrations.AddConstraint(
            model_name='endosso',
            constraint=models.UniqueConstraint(fields=('company', 'apolice', 'numero_endosso'), name='uq_endosso_numero_per_apolice_company'),
        ),
    ]
