# Generated by Django 5.0.2 on 2026-02-08 22:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_company_rbac_overrides'),
        ('operational', '0003_apolice_ai_insights_commercialactivity_ai_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='capture_channel',
            field=models.CharField(choices=[('WEBHOOK', 'Webhook'), ('API', 'API'), ('MANUAL', 'Cadastro Manual'), ('IMPORT', 'Importação')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='cnae_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_size_estimate',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='lead',
            name='external_campaign',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='external_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_response_sla_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_score_label',
            field=models.CharField(blank=True, choices=[('COLD', 'Frio'), ('WARM', 'Morno'), ('HOT', 'Quente')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='needs_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='needs_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_line',
            field=models.CharField(blank=True, choices=[('AUTO', 'Auto'), ('LIFE', 'Vida'), ('HEALTH', 'Saúde'), ('PROPERTY', 'Patrimonial'), ('TRANSPORT', 'Transporte'), ('LIABILITY', 'Responsabilidade Civil'), ('OTHER', 'Outro')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='handover_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='needs_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='product_line',
            field=models.CharField(blank=True, choices=[('AUTO', 'Auto'), ('LIFE', 'Vida'), ('HEALTH', 'Saúde'), ('PROPERTY', 'Patrimonial'), ('TRANSPORT', 'Transporte'), ('LIABILITY', 'Responsabilidade Civil'), ('OTHER', 'Outro')], max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='proposal_pdf_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='proposal_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='proposal_tracking_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='proposal_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='quote_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('NEW', 'Novo/Sem Contato'), ('QUALIFICATION', 'Qualificação'), ('NEEDS_ASSESSMENT', 'Levantamento de Necessidades'), ('QUOTATION', 'Cotação'), ('PROPOSAL_PRESENTATION', 'Apresentação de Proposta'), ('NEGOTIATION', 'Negociação'), ('WON', 'Ganha'), ('LOST', 'Perdida')], default='NEW', max_length=30),
        ),
        migrations.CreateModel(
            name='PolicyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_line', models.CharField(blank=True, choices=[('AUTO', 'Auto'), ('LIFE', 'Vida'), ('HEALTH', 'Saúde'), ('PROPERTY', 'Patrimonial'), ('TRANSPORT', 'Transporte'), ('LIABILITY', 'Responsabilidade Civil'), ('OTHER', 'Outro')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING_DATA', 'Pendente de Dados'), ('UNDER_REVIEW', 'Em Revisão'), ('READY_TO_ISSUE', 'Pronto para Emissão'), ('ISSUED', 'Emitida'), ('REJECTED', 'Rejeitada')], default='PENDING_DATA', max_length=20)),
                ('inspection_required', models.BooleanField(default=True)),
                ('inspection_status', models.CharField(choices=[('NOT_REQUIRED', 'Sem Vistoria'), ('PENDING', 'Vistoria Pendente'), ('SCHEDULED', 'Vistoria Agendada'), ('APPROVED', 'Vistoria Aprovada'), ('REJECTED', 'Vistoria Rejeitada')], default='PENDING', max_length=20)),
                ('inspection_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_notes', models.TextField(blank=True)),
                ('billing_method', models.CharField(blank=True, choices=[('BANK_DEBIT', 'Débito em Conta'), ('INVOICE', 'Boleto'), ('PIX', 'PIX'), ('CREDIT_CARD', 'Cartão de Crédito'), ('OTHER', 'Outro')], max_length=20)),
                ('bank_account_holder', models.CharField(blank=True, max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_branch', models.CharField(blank=True, max_length=20)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('bank_document', models.CharField(blank=True, max_length=20)),
                ('payment_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('final_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('final_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('issue_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_requests', to='operational.customer')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_request', to='operational.opportunity')),
                ('source_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_requests', to='operational.lead')),
            ],
            options={
                'ordering': ('status', 'issue_deadline_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProposalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurer_name', models.CharField(max_length=120)),
                ('plan_name', models.CharField(blank=True, max_length=120)),
                ('coverage_summary', models.TextField(blank=True)),
                ('deductible', models.CharField(blank=True, max_length=120)),
                ('annual_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monthly_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('franchise_notes', models.TextField(blank=True)),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ranking_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_recommended', models.BooleanField(default=False)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_options', to='operational.opportunity')),
            ],
            options={
                'ordering': ('-is_recommended', '-ranking_score', 'annual_premium', '-created_at'),
            },
        ),
    ]
