# Generated by Django 5.0.2 on 2026-02-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational', '0004_lead_capture_channel_lead_cnae_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('NEW', 'Novo/Sem Contato'), ('QUALIFICATION', 'Qualificação'), ('NEEDS_ASSESSMENT', 'Levantamento de Necessidades'), ('QUOTATION', 'Cotação'), ('PROPOSAL_PRESENTATION', 'Apresentação de Proposta'), ('DISCOVERY', 'Descoberta (Legado)'), ('PROPOSAL', 'Proposta (Legado)'), ('NEGOTIATION', 'Negociação'), ('WON', 'Ganha'), ('LOST', 'Perdida')], default='NEW', max_length=30),
        ),
    ]
