# Generated by Django 5.0.2 on 2026-02-09 01:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_company_rbac_overrides'),
        ('operational', '0005_alter_opportunity_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('premium_goal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_goal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('new_customers_goal', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
            ],
            options={
                'verbose_name': 'Meta Comercial',
                'verbose_name_plural': 'Metas Comerciais',
            },
        ),
        migrations.AddConstraint(
            model_name='salesgoal',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month'), name='uq_sales_goal_month_per_company'),
        ),
    ]
