# Generated by Django 5.0.2 on 2026-02-12 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
        ('operational', '0008_installment_operationalintegrationinbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='operational.customer')),
            ],
            options={
                'ordering': ('-is_primary', 'name', 'id'),
                'indexes': [models.Index(fields=['company', 'customer'], name='idx_customer_contact_customer')],
            },
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('company', 'customer'), name='uq_customer_primary_contact_per_customer'),
        ),
    ]
