# Generated by Django 5.0.2 on 2026-02-12 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
        ('operational', '0009_customercontact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect_name', models.CharField(blank=True, max_length=255)),
                ('prospect_document', models.CharField(blank=True, max_length=20)),
                ('prospect_phone', models.CharField(blank=True, max_length=30)),
                ('prospect_email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('TRANSFER_RISK', 'Transferência de Risco (Seguros)'), ('RISK_MANAGEMENT', 'Gestão de Riscos')], max_length=30)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('swot_strengths', models.TextField(blank=True)),
                ('swot_weaknesses', models.TextField(blank=True)),
                ('swot_opportunities', models.TextField(blank=True)),
                ('swot_threats', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado'), ('CLOSED_WON', 'Ganho'), ('CLOSED_LOST', 'Perdido')], default='OPEN', max_length=20)),
                ('loss_reason', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_projects', to='operational.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_special_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SpecialProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('DONE', 'Concluída')], default='OPEN', max_length=10)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='operational.specialproject')),
            ],
            options={
                'ordering': ('status', 'due_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SpecialProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='special_projects/')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operational.specialproject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_special_project_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='specialproject',
            index=models.Index(fields=['company', 'status'], name='idx_special_project_status'),
        ),
        migrations.AddIndex(
            model_name='specialproject',
            index=models.Index(fields=['company', 'project_type'], name='idx_special_project_type'),
        ),
    ]
