# Generated by Django 5.0.2 on 2026-02-12 18:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
        ('operational', '0010_specialproject_specialprojectactivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_text', models.TextField()),
                ('focus', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=14)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('cnpj_profile', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('learned_note', models.TextField(blank=True)),
                ('is_pinned_learning', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('confidence_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company', '-created_at'], name='idx_taii_recent'), models.Index(fields=['company', 'is_pinned_learning'], name='idx_taii_pinned')],
            },
        ),
    ]
