# Generated by Django 5.0.2 on 2026-02-13 09:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_producerprofile_and_more'),
        ('operational', '0011_tenantaiinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AiDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('policy_document', 'Policy Document'), ('special_project_document', 'Special Project Document'), ('generic_document', 'Generic Document')], max_length=40)),
                ('source_id', models.CharField(max_length=64)),
                ('document_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('chunk_text', models.TextField()),
                ('chunk_order', models.PositiveIntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
            ],
            options={
                'ordering': ('source_type', 'source_id', 'chunk_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AiMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], default='user', max_length=20)),
                ('content', models.TextField()),
                ('intent', models.CharField(choices=[('WEB_MARKET', 'Web Market'), ('INTERNAL_ANALYTICS', 'Internal Analytics'), ('CNPJ_ENRICH', 'CNPJ Enrich'), ('DOCS_RAG', 'Docs RAG'), ('SYSTEM_HEALTH', 'System Health'), ('MIXED', 'Mixed')], default='MIXED', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='operational.aiconversation')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AiSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('dashboard', 'Dashboard'), ('finance', 'Finance'), ('sales', 'Sales'), ('operational', 'Operational')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('related_entity_type', models.CharField(blank=True, max_length=80)),
                ('related_entity_id', models.CharField(blank=True, max_length=80)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['company', 'status'], name='idx_aiconv_status'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['company', '-updated_at'], name='idx_aiconv_recent'),
        ),
        migrations.AddIndex(
            model_name='aidocumentchunk',
            index=models.Index(fields=['company', 'source_type', 'source_id'], name='idx_aidoc_src'),
        ),
        migrations.AddIndex(
            model_name='aidocumentchunk',
            index=models.Index(fields=['company', 'created_at'], name='idx_aidoc_ct'),
        ),
        migrations.AddIndex(
            model_name='aidocumentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_aidoc_srch'),
        ),
        migrations.AddConstraint(
            model_name='aidocumentchunk',
            constraint=models.UniqueConstraint(fields=('company', 'source_type', 'source_id', 'chunk_order'), name='uq_aidoc_chunk'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['company', 'conversation'], name='idx_aimsg_conv'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['company', 'intent'], name='idx_aimsg_intent'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['company', 'scope'], name='idx_aisug_scope'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['company', 'expires_at'], name='idx_aisug_exp'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['company', 'seen_at'], name='idx_aisug_seen'),
        ),
    ]
