# Generated by Django 5.0.2 on 2026-02-13 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_commercial_activity_data(apps, schema_editor):
    CommercialActivity = apps.get_model("operational", "CommercialActivity")
    db_alias = schema_editor.connection.alias

    for activity in CommercialActivity.objects.using(db_alias).all().iterator():
        update_fields = set()

        if activity.type != activity.kind:
            activity.type = activity.kind or "TASK"
            update_fields.add("type")
        if not activity.kind:
            activity.kind = activity.type or "TASK"
            update_fields.add("kind")

        if activity.start_at is None:
            activity.start_at = activity.started_at or activity.due_at
            if activity.start_at is not None:
                update_fields.add("start_at")
        if activity.end_at is None and activity.ended_at is not None:
            activity.end_at = activity.ended_at
            update_fields.add("end_at")
        if activity.remind_at is None and activity.reminder_at is not None:
            activity.remind_at = activity.reminder_at
            update_fields.add("remind_at")

        if activity.status == "PENDING":
            activity.status = "OPEN"
            update_fields.add("status")
        elif activity.status == "DONE":
            activity.status = "COMPLETED"
            update_fields.add("status")

        if activity.reminder_sent and activity.reminder_state == "PENDING":
            activity.reminder_state = "SENT"
            update_fields.add("reminder_state")

        origin = None
        # Legacy records could have both lead/opportunity set. Keep OPPORTUNITY as source of truth.
        if activity.opportunity_id:
            origin = "OPPORTUNITY"
        elif activity.lead_id:
            origin = "LEAD"
        elif activity.project_id:
            origin = "PROJECT"
        elif activity.customer_id:
            origin = "CUSTOMER"

        if origin is None:
            # Should not happen in legacy data due prior constraint, but keep deterministic fallback.
            origin = "LEAD"

        if activity.origin != origin:
            activity.origin = origin
            update_fields.add("origin")

        if origin == "LEAD":
            if activity.opportunity_id is not None:
                activity.opportunity_id = None
                update_fields.add("opportunity")
            if activity.project_id is not None:
                activity.project_id = None
                update_fields.add("project")
            if activity.customer_id is not None:
                activity.customer_id = None
                update_fields.add("customer")
        elif origin == "OPPORTUNITY":
            if activity.lead_id is not None:
                activity.lead_id = None
                update_fields.add("lead")
            if activity.project_id is not None:
                activity.project_id = None
                update_fields.add("project")
            if activity.customer_id is not None:
                activity.customer_id = None
                update_fields.add("customer")
        elif origin == "PROJECT":
            if activity.lead_id is not None:
                activity.lead_id = None
                update_fields.add("lead")
            if activity.opportunity_id is not None:
                activity.opportunity_id = None
                update_fields.add("opportunity")
            if activity.customer_id is not None:
                activity.customer_id = None
                update_fields.add("customer")
        elif origin == "CUSTOMER":
            if activity.lead_id is not None:
                activity.lead_id = None
                update_fields.add("lead")
            if activity.opportunity_id is not None:
                activity.opportunity_id = None
                update_fields.add("opportunity")
            if activity.project_id is not None:
                activity.project_id = None
                update_fields.add("project")

        if update_fields:
            update_fields.add("updated_at")
            activity.save(update_fields=sorted(update_fields))


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_producerprofile_and_more'),
        ('operational', '0013_aiassistant_created_at_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialactivity',
            options={'ordering': ('status', 'start_at', 'due_at', '-created_at')},
        ),
        migrations.RemoveConstraint(
            model_name='commercialactivity',
            name='ck_activity_requires_lead_or_opportunity',
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='attendee_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='attendee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_activities', to='operational.customer'),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='origin',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('OPPORTUNITY', 'Opportunity'), ('PROJECT', 'Project'), ('CUSTOMER', 'Customer')], default='LEAD', max_length=20),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_activities', to='operational.specialproject'),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='reminder_state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACKED', 'Acknowledged')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='type',
            field=models.CharField(choices=[('TASK', 'Task'), ('FOLLOW_UP', 'Follow-up'), ('NOTE', 'Note'), ('MEETING', 'Meeting')], default='TASK', max_length=20),
        ),
        migrations.AlterField(
            model_name='commercialactivity',
            name='kind',
            field=models.CharField(choices=[('TASK', 'Task'), ('FOLLOW_UP', 'Follow-up'), ('NOTE', 'Note'), ('MEETING', 'Meeting')], default='TASK', max_length=20),
        ),
        migrations.AlterField(
            model_name='commercialactivity',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending (Legacy)'), ('DONE', 'Done (Legacy)')], default='OPEN', max_length=20),
        ),
        migrations.RunPython(_backfill_commercial_activity_data, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='commercialactivity',
            index=models.Index(fields=['company', 'status', 'start_at'], name='idx_act_company_st_start'),
        ),
        migrations.AddIndex(
            model_name='commercialactivity',
            index=models.Index(fields=['company', 'remind_at'], name='idx_activity_company_remind'),
        ),
        migrations.AddConstraint(
            model_name='commercialactivity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('customer__isnull', True), ('lead__isnull', False), ('opportunity__isnull', True), ('origin', 'LEAD'), ('project__isnull', True)), models.Q(('customer__isnull', True), ('lead__isnull', True), ('opportunity__isnull', False), ('origin', 'OPPORTUNITY'), ('project__isnull', True)), models.Q(('customer__isnull', True), ('lead__isnull', True), ('opportunity__isnull', True), ('origin', 'PROJECT'), ('project__isnull', False)), models.Q(('customer__isnull', False), ('lead__isnull', True), ('opportunity__isnull', True), ('origin', 'CUSTOMER'), ('project__isnull', True)), _connector='OR'), name='ck_activity_origin_matches_relation'),
        ),
    ]
