# Generated by Django 5.0.2 on 2026-02-14 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_tenantemailconfig'),
        ('operational', '0014_alter_commercialactivity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'lifecycle_stage', '-created_at'], name='operational_company_7535c7_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'email'], name='operational_company_b5dd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', '-last_contact_at'], name='operational_company_84fc39_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', '-next_follow_up_at'], name='operational_company_6a0f91_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['assigned_to', '-created_at'], name='operational_assigne_d97396_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'status', '-created_at'], name='operational_company_7776a2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', '-first_response_due_at'], name='operational_company_463076_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'customer', 'status'], name='operational_company_8b715b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'lead_score_label'], name='operational_company_eb9033_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', '-next_follow_up_at'], name='operational_company_ad2623_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', 'stage', '-created_at'], name='operational_company_a1d1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', 'customer', 'stage'], name='operational_company_e74de8_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', '-expected_close_date'], name='operational_company_e60e98_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', 'stage', '-amount'], name='operational_company_d4981d_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', '-next_step_due_at'], name='operational_company_ec3d26_idx'),
        ),
    ]
