# Generated by Django 5.0.2 on 2026-02-10 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_company_schema_name_and_domain'),
        ('insurance_core', '0004_claim_insurancebranch_policybillingconfig_and_more'),
        ('operational', '0008_installment_operationalintegrationinbox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=120)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
            ],
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_name', models.CharField(blank=True, help_text='For external payees (e.g. Insurers)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=20)),
                ('source_ref', models.CharField(blank=True, help_text='Reference to source document (e.g. Batch ID)', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_date',),
            },
        ),
        migrations.CreateModel(
            name='ReceivableInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=20)),
                ('issue_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='operational.customer')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='insurance_core.policy')),
            ],
            options={
                'ordering': ('-issue_date',),
            },
        ),
        migrations.CreateModel(
            name='ReceivableInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='customers.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.receivableinvoice')),
            ],
            options={
                'ordering': ('due_date', 'number'),
            },
        ),
        migrations.AddConstraint(
            model_name='integrationinbox',
            constraint=models.UniqueConstraint(fields=('company', 'event_id'), name='uq_finance_inbox_event_id_company'),
        ),
        migrations.AddConstraint(
            model_name='receivableinstallment',
            constraint=models.UniqueConstraint(fields=('company', 'invoice', 'number'), name='uq_receivable_installment_number'),
        ),
    ]
