# Generated by Django 5.0.2 on 2026-02-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivableinstallment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
